language: node_js
sudo: required
node_js:
  - "6"
  - "node"

services:
  - docker

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  # Docker container for CouchDB 2.0
  - docker run -it -d -p 5984:5984 klaemo/couchdb:2.0-dev --with-admin-party-please --with-haproxy -n 1

cache:
  directories:
    - $HOME/.yarn-cache

before_script:
  - curl -X PUT localhost:5984/got_couch_test
  - curl -X GET localhost:5984/_membership
  # https://github.com/klaemo/docker-couchdb/issues/42#issuecomment-169610897
  - curl -X PUT localhost:5984/_node/node1@127.0.0.1/_config/admins/root -d '"password"'

after_success:
  - bash <(curl -s https://codecov.io/bash)
